spring:
  application:
    name: education-tearcher
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://94.191.60.104:3306/education?useUnicode=true&characterEncoding=utf-8
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    password: 123456
  mvc:
    view:
      suffix: .html
      prefix: /

server:
  port: 8082

logging:
  config: classpath:log.xml

teacher:
   config:
     dictionaryId: 12



