spring:
  application:
    name: education-student
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://94.191.60.104:3306/education?useUnicode=true&characterEncoding=utf-8
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    password: 123456
upload:
   config:
      filePath: C:\work\upload
server:
  port: 8081

logging:
  config: classpath:log.xml

student:
   config:
     toke: dsfsasredserwersdfdsf
      studentUrl: http://localhost:8082/teacher/teacher/common/command

