spring:
  application:
    name: education-web
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://94.191.60.104:3306/education?useUnicode=true&characterEncoding=utf-8
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    password: 123456
  mvc:
    view:
      suffix: .html
      prefix: /login.html
  http:
    multipart:
      enabled: true
upload:
   config:
      filePath: C:\work\upload

server:
  port: 8083
  session:
    timeout: 3600

logging:
  config: classpath:log.xml




